kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: fogproject
spec:
  rules:
    - host: fogproject.sj.ifsc.edu.br
      http:
        paths:
          - path: /
            backend:
              serviceName: fogproject
              servicePort: 80
