apiVersion: v1
kind: Service
metadata:
  name: fogproject-ports-tcp
spec:
  selector:
    app: fogproject
  externalIPs:
    - "191.36.8.4"
    - "191.36.8.5"
  ports:
    - name: nfs
      protocol: TCP
      port: 2049
      targetPort: 2049
    - name: ftp
      protocol: TCP
      port: 21
      targetPort: 21
    - name: rpcbind
      protocol: TCP
      port: 111
      targetPort: 111
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: fogproject
spec:
  selector:
    app: fogproject
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: fogproject-ports-udp
  spec:
    selector:
      app: fogproject
    externalIPs:
      - "191.36.8.4"
      - "191.36.8.5"
    ports:
      - name: nfs
        protocol: UDP
        port: 2049
        targetPort: 2049
      - name: rpcbind
        protocol: UDP
        port: 111
        targetPort: 111
      - name: tftp
        protocol: UDP
        port: 69
        targetPort: 69
    type: LoadBalancer
