apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: puppet
  name: puppet
spec:
  ports:
  - name: "8140"
    port: 8140
    targetPort: 8140
  selector:
    io.kompose.service: puppet
status:
  loadBalancer: {}
