apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: puppetexplorer
  name: puppetexplorer
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: puppetexplorer
status:
  loadBalancer: {}
