apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: puppetboard
  name: puppetboard
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: puppetboard
    spec:
      containers:
      - image: puppet/puppetboard
        name: puppetboard
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
