apiVersion: v1
kind: Service
metadata:
  labels:
    app: puppet-postgres
  name: puppet-postgres
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: puppet-postgres

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: puppet-puppetdb
  name: puppet-puppetdb
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: puppet-puppetdb

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: puppet-puppetboard
  name: puppet-puppetboard
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: puppet-puppetboard

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: puppet-puppetexplorer
  name: puppet-puppetexplorer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: puppet-puppetexplorer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: puppet-puppetserver
  name: puppet-puppetserver
spec:
  externalIPs:
    - "191.36.8.4"
    - "191.36.8.5"
    - "191.36.8.6"
    - "191.36.8.7"
    - "191.36.8.8"
  ports:
  - name: https
    port: 8140
    protocol: TCP
    targetPort: 8140
  selector:
    app: puppet-puppetserver
  type: LoadBalancer
