kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-mariadb
  labels:
    app: wordpress-mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8400Mi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-wordpress
  labels:
    app: wordpress-wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10100Mi
