apiVersion: v1
kind: Service
metadata:
  name: wordpress-mariadb
  labels:
    app: wordpress-mariadb
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: wordpress-mariadb

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: wordpress-wordpress
