apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcmariadb
  annotations:
    volume.beta.kubernetes.io/storage-class: storageclassretain
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
