kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pji11103a-mongo
  labels:
    projeto: pji11103a
    app: mongo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pji11103a-html
  labels:
    projeto: pji11103a
    app: html
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
