apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-dev-nginx-conf
data:
  nginx.conf: |-
    # https://mozilla.github.io/server-side-tls/ssl-config-generator/
    # https://www.ssllabs.com/ssltest/analyze.html?d=chat.sj.ifsc.edu.br
    # https://www.networking4all.com/en/support/
    events {
        worker_connections 1024;
    }
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        gzip on;
        server {
            listen 80;
            server_name gtampto.sj.ifsc.edu.br;
            location / {
                return 301 https://wordpress.sj.ifsc.edu.br/gtampto$request_uri;
            }
        }
        server {
            listen 80;
            server_name mcc2014.sj.ifsc.edu.br;
            location / {
                return 301 https://wordpress.sj.ifsc.edu.br/mcc2014$request_uri;
            }
        }
        server {
            listen 80;
            server_name mcc2016.sj.ifsc.edu.br;
            location / {
                return 301 https://wordpress.sj.ifsc.edu.br/mcc2016$request_uri;
            }
        }
        server {
            listen 80;
            server_name sel.sj.ifsc.edu.br;
            location / {
                return 301 https://wordpress.sj.ifsc.edu.br/sel$request_uri;
            }
        }
        server {
            listen 80 default_server;
            location /status {
                stub_status on;
                access_log off;
                allow 10.0.0.0/8;
                deny all;
            }
            location / {
                return 301 https://$host$request_uri;
            }
        }
        upstream hugo {
            server hugo;
        }
        upstream wordpress {
            server wordpress:443;
        }
        server {
            index index.php;
            listen 443 ssl http2;
            server_name wordpress;
            server_name wordpress.sj.ifsc.edu.br;
            server_name gtampto.sj.ifsc.edu.br;
            server_name mcc2014.sj.ifsc.edu.br;
            server_name mcc2016.sj.ifsc.edu.br;
            server_name sel.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass https://wordpress/;
                proxy_set_header Host $http_host;
                client_max_body_size 100M;
            }
        }
    }
