apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-dev
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      containers:
        - image: nginx:1.13.1
          name: nginx-dev
          livenessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: nginx-dev-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-dev-nginx-ssl
              mountPath: /etc/certs/
              readOnly: true
      restartPolicy: Always
      volumes:
      - name: nginx-dev-nginx-conf
        configMap:
          name: nginx-dev-nginx-conf
      - name: nginx-dev-nginx-ssl
        secret:
          secretName: nginx-dev-nginx-ssl
          items:
            - key: ca.pem
              path: "ca.pem"
            - key: cert.pem
              path: "cert.pem"
            - key: key.pem
              path: "key.pem"
