kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: mosquitto
  annotations:
    kubernetes.io/ingress.class: tectonic
spec:
  tls:
    - hosts:
        - mqtt.sj.ifsc.edu.br
      secretName: tls-ifsc-sje
  rules:
    - host: mqtt.sj.ifsc.edu.br
      http:
        paths:
          - path: /
            backend:
              serviceName: mosquitto-ws
              servicePort: 8083
status:
  loadBalancer:
    ingress:
      - ip: 191.36.8.24
      - ip: 191.36.8.25
