apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-mosquitto-conf
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/mosquitto/mosquitto/conf

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-mosquitto-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/mosquitto/mosquitto/data
