apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: economizei-bd
  namespace: ensino
  labels:
    curso: integrado
    disciplina: arc60808
    projeto: economizei
    app: mariadb
    tier: backend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: economizei-bd
