apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatbot
  labels:
    app: chatbot
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/ctic/chatbot
