apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: arduino-iot-mongo
  namespace: pesquisa
  labels:
    namespace: pesquisa
    projeto: arduino-iot
    app: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        namespace: pesquisa
        projeto: arduino-iot
        app: mongo
    spec:
      containers:
        - image: mongo:3.4
          name: arduino-iot-mongo
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 2
              memory: 1024Mi
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db/
      restartPolicy: Always
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: arduino-iot-mongo
