apiVersion: v1
kind: PersistentVolume
metadata:
  name: arduino-iot-mongo
  labels:
    namespace: pesquisa
    projeto: arduino-iot
    app: mongo
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/pesquisa/arduino-iot/mongo
