# PV

apiVersion: v1
kind: PersistentVolume
metadata:
  name: netbox-postgresql-base
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/netbox/postgresql/base

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: netbox-netbox-conf
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/netbox/netbox/conf

---

# PVC

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netbox-postgresql-base
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netbox-netbox-conf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

---

# Secret

apiVersion: v1
kind: Secret
metadata:
  name: netbox
type: Opaque
data:
  postgresql_password: YWRtaW4=
  netbox_username: YWRtaW4=
  netbox_password: YWRtaW4=
  netbox_email: Y3RpYy5zamVAbGlzdGFzLnNqLmlmc2MuZWR1LmJy
  netbox_super_username: YWRtaW4=

---

# Deployment

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netbox-postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: netbox
        type: backend
    spec:
      containers:
        - image: postgres
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox
                  key: postgresql_password
            - name: POSTGRES_DB
              value: netbox
          #ports:
          #  - containerPort: 5432
          volumeMounts:
            - name: netbox-postgresql-base
              mountPath: /var/lib/postgresql
      restartPolicy: Always
      volumes:
      - name: netbox-postgresql-base
        persistentVolumeClaim:
          claimName: netbox-postgresql-base
      - name: netbox
        secret:
          secretName: netbox

---

# Service

# _postgres._tcp.netbox.default.default.local
#kind: Service
#apiVersion: v1
#metadata:
#  name: netbox-postgresql
#spec:
#  selector:
#    app: netbox
#  ports:
#    - protocol: TCP
#      port: 5432
#      targetPort: 5432
