apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-db
spec:
  capacity:
    storage: 162Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/zabbix/db
