kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: chatbot
  namespace: ctic
  labels:
    app: chatbot
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
