apiVersion: rook.io/v1alpha1
kind: Filesystem
metadata:
  name: rocketchat
  namespace: rook
spec:
  metadataPool:
    replicated:
      size: 2
  dataPools:
    - replicated:
        size: 2
  metadataServer:
    activeCount: 1
    activeStandby: true
