kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: tectonic
  name: rocketchat
  namespace: default
spec:
  tls:
    - hosts:
        - chat.sj.ifsc.edu.br
      secretName: tls-ifsc-sje
  rules:
    - host: chat.sj.ifsc.edu.br
      http:
        paths:
          - path: /
            backend:
              serviceName: rocketchat
              servicePort: 80
