kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rocketchat-storage-pvc
  labels:
    app: rocketchat
    tier: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rocketchat-storage