apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketchat-storage-pv
  labels:
    app: rocketchat
    tier: backend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/rocket.chat
