apiVersion: v1
kind: Service
metadata:
  name: rocketchat-database
  namespace: default
  labels:
    app: rocketchat
    tier: backend
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    app: rocketchat
    tier: backend

---

apiVersion: v1
kind: Service
metadata:
  name: rocketchat
  namespace: default
  labels:
    app: rocketchat
    tier: frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: rocketchat
    tier: frontend
