kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: arc60808
  namespace: ensino
  labels:
    namespace: ensino
    app: arc60808
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
