apiVersion: v1
kind: PersistentVolume
metadata:
  name: arc60808
  labels:
    namespace: ensino
    app: arc60808
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/ensino/arc60808
