apiVersion: v1
kind: Service
metadata:
  labels:
    app: bcd29008
  name: bcd29008
spec:
  externalIPs:
    - "191.36.8.24"
    - "191.36.8.25"
  ports:
    - name: mysql
      port: 13306
      protocol: TCP
      targetPort: 3306
  selector:
    app: bcd29008-mysql
  type: LoadBalancer
