apiVersion: v1
kind: PersistentVolume
metadata:
  name: arc60808-rotas
  namespace: ensino
  labels:
    namespace: ensino
    course: arc60808
    app: rotas
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/ensino/arc60808/rotas
