apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kididcca-mongo
  labels:
    projeto: kididcca
    app: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        projeto: kididcca
        app: mongo
    spec:
      containers:
        - image: mongo:3.4
          name: kididcca-mongo
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 2
              memory: 1024Mi
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db/
      restartPolicy: Always
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: kididcca-mongo

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kididcca-mqtt-mongo
  labels:
    projeto: kididcca
    app: mqtt-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        projeto: kididcca
        app: mqtt-mongo
    spec:
      containers:
        - image: kididcca/mqtt-mongo:latest
          name: kididcca-mqtt-mongo
          env:
          - name: MONGO_SERVER
            value: "kididcca-mongo"
          - name: DATABASE
            value: "estacao0"
          - name: MQTT_BROKER
            value: "mqtt.sj.ifsc.edu.br"
          - name: TOPIC
            value: "estacao0/#"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 512Mi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kididcca-mongo-html
  labels:
    projeto: kididcca
    app: mongo-html
spec:
  replicas: 1
  template:
    metadata:
      labels:
        projeto: kididcca
        app: mongo-html
    spec:
      containers:
        - image: kididcca/mongo-html:latest
          name: kididcca-mongo-html
          env:
          - name: MONGO_SERVER
            value: "kididcca-mongo"
          - name: DATABASE
            value: "estacao0"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            - name: html
              mountPath: /cron/html
      restartPolicy: Always
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: kididcca-html

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kididcca-nginx
  labels:
    projeto: kididcca
    app: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        projeto: kididcca
        app: nginx
    spec:
      containers:
        - image: nginx:1.13
          name: kididcca-nginx
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: True
      restartPolicy: Always
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: kididcca-html
