apiVersion: v1
kind: PersistentVolume
metadata:
  name: kididcca-mongo
  labels:
    projeto: kididcca
    app: mongo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/pesquisa/kididcca/mongo

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kididcca-html
  labels:
    projeto: kididcca
    app: html
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/pesquisa/kididcca/html
