apiVersion: v1
kind: Service
metadata:
  labels:
    projeto: kididcca
    app: mongo
  name: kididcca-mongo
spec:
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    projeto: kididcca
    app: mongo

---

apiVersion: v1
kind: Service
metadata:
  labels:
    projeto: kididcca
    app: nginx
  name: kididcca-nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    projeto: kididcca
    app: nginx
