apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mediawiki-mariadb
  labels:
    app: mediawiki-mariadb
spec:
  template:
    metadata:
      labels:
        app: mediawiki-mariadb
      annotations:
        pod.alpha.kubernetes.io/init-containers: '
          [
            {
              "name": "copy-custom-config",
              "image": "bitnami/mariadb:10.1.23-r2",
              "command": ["sh", "-c", "mkdir -p /bitnami/mariadb/conf && cp -n /bitnami/mariadb_config/my.cnf /bitnami/mariadb/conf/my_custom.cnf"],
              "volumeMounts": [
                {
                  "name": "config",
                  "mountPath": "/bitnami/mariadb_config"
                },
                {
                  "name": "data",
                  "mountPath": "/bitnami/mariadb"
                }
              ]
            }
          ]'
    spec:
      containers:
      - name: mediawiki-mariadb
        image: "bitnami/mariadb:10.1.23-r2"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mediawiki-mariadb
              key: mariadb-root-password
        - name: MARIADB_USER
          value:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mediawiki-mariadb
              key: mariadb-password
        - name: MARIADB_DATABASE
          value:
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
          memory: 256Mi
          cpu: 250m
        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
      volumes:
      - name: config
        configMap:
          name: mediawiki-mariadb
      - name: data
        persistentVolumeClaim:
          claimName: mediawiki-mariadb
        emptyDir: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mediawiki-mediawiki
  labels:
    app: mediawiki-mediawiki
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mediawiki-mediawiki
    spec:
      containers:
      - name: mediawiki-mediawiki
        image: "bitnami/mediawiki:1.28.2-r1"
        env:
        - name: MARIADB_HOST
          value:
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name:
              key: mariadb-root-password
        - name: MEDIAWIKI_USERNAME
          value:
        - name: MEDIAWIKI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mediawiki-mediawiki
              key: mediawiki-password
        - name: MEDIAWIKI_EMAIL
          value:
        - name: MEDIAWIKI_WIKI_NAME
          value:
        - name: SMTP_HOST_ID
          value:
        - name: SMTP_HOST
          value:
        - name: SMTP_PORT
          value:
        - name: SMTP_USER
          value:
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mediawiki-mediawiki
              key: smtp-password
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
          memory: 512Mi
          cpu: 300m
        volumeMounts:
        - name: mediawiki-data
          mountPath: /bitnami/mediawiki
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: mediawiki-data
        persistentVolumeClaim:
          claimName: mediawiki-mediawiki
        emptyDir: {}
      - name: apache-data
        persistentVolumeClaim:
          claimName: mediawiki-apache
        emptyDir: {}
