kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: mediawiki
  annotations:
    kubernetes.io/ingress.class: tectonic
spec:
  tls:
    - hosts:
        - mediawiki.sj.ifsc.edu.br
      secretName: tls-ifsc-sje
    - hosts:
        - cicd.sj.ifsc.edu.br
      secretName: tls-ifsc-sje
  rules:
    - host: mediawiki.sj.ifsc.edu.br
      http:
        paths:
          - path: /
            backend:
              serviceName: mediawiki
              servicePort: 80
    - host: cicd.sj.ifsc.edu.br
      http:
        paths:
          - path: /
            backend:
              serviceName: mediawiki
              servicePort: 80
status:
  loadBalancer:
    ingress:
      - ip: 191.36.8.24
      - ip: 191.36.8.25
