apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-apache
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/mediawiki/apache

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-mariadb
spec:
  capacity:
    storage: 9Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/mediawiki/mariadb

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-mediawiki
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/mediawiki/mediawiki

      
