apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto
  namespace: producao
spec:
  externalIPs:
    - "191.36.8.21"
    - "191.36.8.22"
    - "191.36.8.23"
    - "191.36.8.24"
    - "191.36.8.25"
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    app: mosquitto
  type: LoadBalancer
