apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: belmiroj-mysql
  labels:
    aluno: belmiroj
    curso: "207"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
