apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-nginx-conf
data:
  nginx.conf: |-
    # https://mozilla.github.io/server-side-tls/ssl-config-generator/
    # https://www.ssllabs.com/ssltest/analyze.html?d=chat.sj.ifsc.edu.br
    # https://www.networking4all.com/en/support/
    events {
        worker_connections 1024;
    }
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        gzip on;
        server {
            listen 80 default_server;
            location /status {
                stub_status on;
                access_log off;
                allow 10.0.0.0/8;
                deny all;
            }
            location / {
                return 301 https://$host$request_uri;
            }
        }
        upstream hugo {
            server hugo;
        }
        server {
            listen 443 ssl http2;
            server_name nuvem;
            server_name nuvem.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://hugo/;
                proxy_set_header Host $http_host;
            }
        }
        upstream netbox {
            server netbox;
        }
        server {
            listen 443 ssl http2;
            server_name netbox;
            server_name netbox.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://netbox/;
                proxy_set_header Host $http_host;
                add_header P3P 'CP="ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"';
            }
        }
        upstream zabbix {
            server zabbix;
        }
        server {
            listen 443 ssl http2;
            server_name zabbix;
            server_name zabbix.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://zabbix/;
                proxy_set_header Host $http_host;
                add_header P3P 'CP="ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"';
            }
        }
        upstream wordpress {
            server wordpress:443;
        }
        server {
            listen 443 ssl http2;
            server_name wordpress;
            server_name wordpress.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass https://wordpress/;
                proxy_set_header Host $http_host;
            }
        }
        upstream rocketchat {
            server rocketchat:3000;
        }
        server {
            listen 443 ssl http2;
            server_name chat;
            server_name chat.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://rocketchat/;
                proxy_set_header Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }
        }
        upstream sharelatex {
            server sharelatex;
        }
        server {
            listen 443 ssl http2;
            server_name sharelatex;
            server_name sharelatex.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://sharelatex/;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }
        }
        upstream mediawiki {
            server mediawiki;
        }
        server {
            listen 443 ssl http2;
            server_name cicd;
            server_name cicd.sj.ifsc.edu.br;
            server_name mediawiki;
            server_name mediawiki.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://mediawiki/;
                proxy_set_header Host $http_host;
            }
        }
        upstream owncloud {
            server owncloud;
        }
        server {
            listen 443 ssl http2;
            server_name owncloud;
            server_name owncloud.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://owncloud/;
                proxy_set_header Host $http_host;
            }
        }
        upstream nextcloud {
            server nextcloud:8080;
        }
        server {
            listen 443 ssl http2;
            server_name nextcloud;
            server_name nextcloud.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security "max-age=15768000; includeSubDomains;";
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://nextcloud/;
                proxy_set_header Host $http_host;
            }
        }
        upstream openproject {
            server openproject;
        }
        server {
            listen 443 ssl http2;
            server_name openproject;
            server_name openproject.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security "max-age=15768000; includeSubDomains;";
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://openproject/;
                proxy_set_header Host $http_host;
            }
        }
        upstream puppetdb {
            server puppetdb:8080;
        }
        server {
            listen 443 ssl http2;
            server_name puppetdb;
            server_name puppetdb.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://puppetdb/;
                proxy_set_header Host $http_host;
            }
        }
        upstream puppetexplorer {
            server puppetexplorer;
        }
        server {
            listen 443 ssl http2;
            server_name puppetexplorer;
            server_name puppetexplorer.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://puppetexplorer/;
                proxy_set_header Host $http_host;
            }
        }
        upstream puppetboard {
            server puppetboard:8000;
        }
        server {
            listen 443 ssl http2;
            server_name puppetdashboard;
            server_name puppetdashboard.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass http://puppetboard/;
                proxy_set_header Host $http_host;
            }
        }
        upstream mosquitto {
            server mosquitto-ws:8083;
        }
        server {
            listen 443 ssl http2;
            server_name mqtt;
            server_name mqtt.sj.ifsc.edu.br;
            ssl_certificate /etc/certs/cert.pem;
            ssl_certificate_key /etc/certs/key.pem;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;
            add_header Strict-Transport-Security max-age=15768000;
            ssl_stapling on;
            ssl_stapling_verify on;
            ssl_trusted_certificate /etc/certs/ca.pem;
            location / {
                proxy_http_version 1.1;
                proxy_pass https://mosquitto/;
                proxy_set_header Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
           }
        }

    }
