apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.13.1
          name: nginx-nginx
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: nginx-nginx-conf
              mountPath: /etc/nginx/
      restartPolicy: Always
      volumes:
      - name: nginx-nginx-conf
        configMap:
          name: nginx-nginx-conf
          items:
          - path: "mime.types"
            key: mime.types
          - path: "nginx.conf"
            key: nginx.conf
          - path: "netbox.crt"
            key: netbox.crt
          - path: "netbox.key"
            key: netbox.key
          - path: "rocketchat.crt"
            key: rocketchat.crt
          - path: "rocketchat.key"
            key: rocketchat.key
          - path: "sharelatex.crt"
            key: sharelatex.crt
          - path: "sharelatex.key"
            key: sharelatex.key
          - path: "che.crt"
            key: che.crt
          - path: "che.key"
            key: che.key
          - path: "mosquitto.crt"
            key: mosquitto.crt
          - path: "mosquitto.key"
            key: mosquitto.key
