apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.13.1
          name: nginx-nginx
          livenessProbe:
            httpGet:
              path: /metrics
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: nginx-nginx-conf
              mountPath: /etc/nginx/
              readOnly: true
            - name: nginx-nginx-ssl
              mountPath: /etc/certs/
              readOnly: true
      restartPolicy: Always
      volumes:
      - name: nginx-nginx-conf
        configMap:
          name: nginx-nginx-conf
          items:
          - key: mime.types
            path: "mime.types"
          - key: nginx.conf
            path: "nginx.conf"
      - name: nginx-nginx-ssl
        secret:
          secretName: nginx-nginx-ssl
          items:
            - key: ca.pem
              path: "ca.pem"
            - key: cert.pem
              path: "cert.pem"
            - key: key.pem
              path: "key.pem"
