apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nginx-conf
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/nginx/nginx/conf