apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heyceitas-bd
  namespace: ensino
  labels:
    curso: integrado
    disciplina: arc60808
    projeto: heyceitas
    app: mariadb
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        curso: integrado
        disciplina: arc60808
        projeto: heyceitas
        app: mariadb
        tier: backend
    spec:
      containers:
      - name: heyceitas-bd
        image: docker.io/mariadb:10.2
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: heyceitas-bd
              key: senha
        - name: MYSQL_DATABASE
          value: heyceitas
        - name: MYSQL_USER
          value: heyceitas
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: heyceitas-bd
              key: senha
        ports:
        - name: mysql
          containerPort: 3306
        resources:
            requests:
              cpu: 500m
              memory: 512m
            limits:
              cpu: 2
              memory: 1Gi
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: heyceitas-bd
