apiVersion: v1
kind: PersistentVolume
metadata:
  name: heyceitas-bd
  namespace: ensino
  labels:
    curso: integrado
    disciplina: arc60808
    projeto: heyceitas
    app: mariadb
    tier: backend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: heyceitas-bd
  mountOptions:
    - nolock
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/ensino/arc60808/heyceitas/mariadb
