apiVersion: v1
kind: Service
metadata:
  name: heyceitas-bd
  namespace: ensino
  labels:
    curso: integrado
    disciplina: arc60808
    projeto: heyceitas
    app: mariadb
    tier: backend
spec:
  externalIPs:
    - "191.36.8.21"
    - "191.36.8.22"
    - "191.36.8.23"
    - "191.36.8.24"
    - "191.36.8.25"
  ports:
    - name: mysql
      port: 13306
      protocol: TCP
      targetPort: 3306
  selector:
    curso: integrado
    disciplina: arc60808
    projeto: heyceitas
    app: mariadb
    tier: backend
  type: LoadBalancer

