kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: owncloud-apache
  labels:
    app: owncloud-apache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1200Mi

---
    
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: owncloud-mariadb
  labels:
    app: owncloud-mariadb

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8500Mi
      
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: owncloud-owncloud
  labels:
    app: owncloud-owncloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8600Mi
