apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nextcloud-mariadb
  labels:
    app: nextcloud-mariadb
spec:
  template:
    metadata:
      labels:
        app: nextcloud-mariadb
      annotations:
        pod.alpha.kubernetes.io/init-containers: '
          [
            {
              "name": "copy-custom-config",
              "image": "bitnami/mariadb:10.1.23-r2",
              "command": ["sh", "-c", "mkdir -p /bitnami/mariadb/conf && cp -n /bitnami/mariadb_config/my.cnf /bitnami/mariadb/conf/my_custom.cnf"],
              "volumeMounts": [
                {
                  "name": "config",
                  "mountPath": "/bitnami/mariadb_config"
                },
                {
                  "name": "data",
                  "mountPath": "/bitnami/mariadb"
                }
              ]
            }
          ]'
    spec:
      containers:
      - name: nextcloud-mariadb
        image: "bitnami/mariadb:10.1.23-r2"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-db
              key: db-root-password
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-db
              key: db-password
        - name: MARIADB_DATABASE
          value: nextcloud
        - name: MARIADB_USER
          value: nextcloud
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
      volumes:
      - name: config
        configMap:
          name: nextcloud-mariadb
      - name: data
        persistentVolumeClaim:
          claimName: nextcloud-mariadb

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nextcloud-redis
  name: nextcloud-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud-redis
    spec:
      containers:
      - image: redis:alpine
        name: nextcloud-redis
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /data
          name: nextcloud-redis
      restartPolicy: Always
      volumes:
      - name: nextcloud-redis
        persistentVolumeClaim:
          claimName: nextcloud-redis

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nextcloud-collabora
  name: nextcloud-collabora
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nextcloud-collabora
    spec:
      containers:
      - env:
        - name: username
          value: cticsje
        - name: password
          value: teste123
        - name: server_name
          value: collabora.sj.ifsc.edu.br
        - name: domain
          value: collabora.sj.ifsc.edu.br
        image: collabora/code
        name: nextcloud-collabora
        ports:
        - containerPort: 9980
        resources: {}
        securityContext:
          capabilities:
            add:
            - MKNOD
      restartPolicy: Always

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nextcloud-nextcloud
  name: nextcloud-nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud-nextcloud
    spec:
      containers:
      - image: nextcloud
        name: nextcloud-nextcloud
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 512Mi
            cpu: 300m
        volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud-data
      restartPolicy: Always
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data
