apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud-data
  name: nextcloud-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud-redis
  name: nextcloud-redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 311Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud-mariadb
  name: nextcloud-mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8890Mi
