apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/nextcloud/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis
spec:
  capacity:
    storage: 311Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/nextcloud/redis
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-mariadb
spec:
  capacity:
    storage: 8890Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/nextcloud/mariadb
