apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mariadb
  labels:
    app: nextcloud-mariadb
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: nextcloud-mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-redis
spec:
  ports:
  - name: nextcloud-redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: nextcloud-redis
    
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: collabora
  name: collabora
spec:
  ports:
  - name: collabora
    port: 9980
    targetPort: collabora
  selector:
    app: nextcloud-collabora
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    app: nextcloud-nextcloud
