apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: arc60808-chatbot-slack-julinho
  labels:
    course: arc60808
    app: chatbot-slack
    bot: julinho
spec:
  replicas: 1
  template:
    metadata:
      labels:
        course: arc60808
        app: chatbot-slack
        bot: julinho
    spec:
      containers:
        - image: cticsjeifsc/errbot
          name: arc60808-chatbot-slack-julinho
          env:
          - name: KEY_PATH
            value: "/errbot/private.key"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 2
              memory: 512Mi
          volumeMounts:
            - name: secret
              mountPath: /errbot/config.py
              subPath: config.py
              readOnly: true
            - name: secret
              mountPath: /errbot/private.key
              subPath: private.key
              readOnly: true
            - name: secret
              mountPath: /errbot/public.pem
              subPath: public.pem
              readOnly: true
            - name: data
              mountPath: /errbot/data/
      restartPolicy: Always
      volumes:
      - name: secret
        secret:
          secretName: arc60808-chatbot-slack-julinho
      - name: data
        persistentVolumeClaim:
          claimName: arc60808-chatbot-slack-julinho
