apiVersion: v1
kind: Namespace
metadata:
  name: rook

---

apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  dataDirHostPath: /var/lib/rook
  storage:
    useAllNodes: true
    useAllDevices: true
    storeConfig:
      storeType: bluestore
      databaseSizeMB: 1024
      journalSizeMB: 1024

---

apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: srv
  namespace: rook
spec:
  replicated:
    size: 2

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: srv-pool
   namespace: rook
provisioner: rook.io/block
parameters:
  pool: srv
