apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: hugo-web
  name: hugo-web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 110Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: hugo-hugo-output
  name: hugo-hugo-output
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 111Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: hugo-hugo-src
  name: hugo-hugo-src
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 112Mi
