# subpath https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: octave
  labels:
    app: octave
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: octave
    spec:
      containers:
      - name: octave
        image: cticsjeifsc/octave
        ports:
        - name: ssh
          containerPort: 22
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 4Gi
        volumeMounts:
        - name: octave-home
          mountPath: /home
        - name: octave-users
          mountPath: /etc/shadow
          subPath: shadow
        - name: octave-users
          mountPath: /etc/passwd
          subPath: passwd
        - name: octave-users
          mountPath: /etc/group
          subPath: group
        - name: nsswitch-ldap-conf
          mountPath: /etc/nsswitch.conf
          subPath: nsswitch.conf
        - name: libnss-ldap-conf
          mountPath: /etc/libnss-ldap.conf
          subPath: libnss-ldap.conf
        - name: pam-ldap-conf
          mountPath: /etc/pam_ldap.conf
          subPath: pam_ldap.conf
        - name: pam-common-session
          mountPath: /etc/pam.d/common-session
          subPath: common-session
      volumes:
      - name: octave-home
        persistentVolumeClaim:
          claimName: octave-home
      - name: octave-users
        persistentVolumeClaim:
          claimName: octave-users
      - name: nsswitch-ldap-conf
        configMap:
          name: nsswitch-ldap-conf
      - name: pam-ldap-conf
        configMap:
          name: pam-ldap-conf
      - name: libnss-ldap-conf
        configMap:
          name: libnss-ldap-conf
      - name: pam-common-session
        configMap:
          name: pam-common-session
