# subpath https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: octave
  labels:
    app: octave
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: octave
    spec:
      containers:
      - name: octave
        image: ??????????
        ports:
        - name: ssh
          containerPort: 22
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 3Gi
        volumeMounts:
        - name: matlab-home
          mountPath: /home
        - name: matlab-users
          mountPath: /etc/shadow
          subPath: shadow
        - name: matlab-users
          mountPath: cat /etc/passwd
          subPath: passwd
        - name: matlab-users
          mountPath: /etc/group
          subPath: group
      volumes:
      - name: matlab-home
        persistentVolumeClaim:
          claimName: matlab-home
      - name: matlab-users
        persistentVolumeClaim:
          claimName: matlab-users
