apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: octave
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: octave
  targetCPUUtilizationPercentage: 80
