apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: onlyoffice-documentserver
  name: onlyoffice-documentserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: onlyoffice-documentserver
    spec:
      containers:
      - env:
        - name: SSL_CERTIFICATE_PATH
          value: /mnt/cert.pem
        - name: SSL_KEY_PATH
          value: /mnt/key.pem
          POSTGRESQL_SERVER_HOST:
          POSTGRESQL_SERVER_PORT:
          POSTGRESQL_SERVER_DB_NAME:
          POSTGRESQL_SERVER_USER:
          POSTGRESQL_SERVER_PASS:
          RABBITMQ_SERVER_HOST:
          RABBITMQ_SERVER_USER:
          RABBITMQ_SERVER_PASS:
          REDIS_SERVER_HOST: 
          REDIS_SERVER_PORT:
          
        image: onlyoffice/documentserver:latest
        name: onlyoffice-documentserver
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /var/www/onlyoffice/Data
          name: onlyoffice-onlyoffice-data
        - mountPath: /var/lib/onlyoffice
          name: onlyoffice-onlyoffice-cache
        - mountPath: /var/log/onlyoffice
          name: onlyoffice-onlyoffice-log
        - mountPath: /var/lib/postgresql
          name: onlyoffice-postgresql
        - mountPath: /mnt/
          name: nginx-nginx-ssl
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: onlyoffice-onlyoffice-data
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-data
      - name: onlyoffice-onlyoffice-cache
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-cache
      - name: onlyoffice-onlyoffice-log
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-log
      - name: onlyoffice-postgresql
        persistentVolumeClaim:
          claimName: onlyoffice-postgresql
      - name: nginx-nginx-ssl
        secret:
          secretName: nginx-nginx-ssl
          items:
            - key: ca.pem
              path: "ca.pem"
            - key: cert.pem
              path: "cert.pem"
            - key: key.pem
              path: "key.pem"
