apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: onlyoffice-redis
  name: onlyoffice-redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: onlyoffice-redis
    spec:
      containers:
      - image: redis
        name: onlyoffice-redis
        resources: {}
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: onlyoffice-rabbitmq
  name: onlyoffice-rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: onlyoffice-rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: onlyoffice-rabbitmq
        resources: {}
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: onlyoffice-postgresql
  name: onlyoffice-postgresql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: onlyoffice-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: onlyoffice
        - name: POSTGRES_USER
          value: onlyoffice
        image: postgres:9.5
        name: onlyoffice-postgresql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: onlyoffice-postgresql
      restartPolicy: Always
      volumes:
      - name: onlyoffice-postgresql
        persistentVolumeClaim:
          claimName: onlyoffice-postgresql
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: onlyoffice-documentserver
  name: onlyoffice-documentserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: onlyoffice-documentserver
    spec:
      containers:
      - env:
        - name: SSL_CERTIFICATE_PATH
          value: /mnt/cert.pem
        - name: SSL_KEY_PATH
          value: /mnt/key.pem
        - name: POSTGRESQL_SERVER_DB_NAME
          value: onlyoffice
        - name: POSTGRESQL_SERVER_HOST
          value: onlyoffice-postgresql
        - name: POSTGRESQL_SERVER_PORT
          value: "5432"
        - name: POSTGRESQL_SERVER_USER
          value: onlyoffice
        - name: REDIS_SERVER_HOST
          value: onlyoffice-redis
        - name: REDIS_SERVER_PORT
          value: "6379"
        image: onlyoffice/documentserver:latest
        name: onlyoffice-documentserver
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /var/www/onlyoffice/Data
          name: onlyoffice-onlyoffice-data
        - mountPath: /usr/share/fonts/truetype/custom
          name: onlyoffice-onlyoffice-fonts
        - mountPath: /var/log/onlyoffice
          name: onlyoffice-onlyoffice-log
        - mountPath: /mnt/
          name: nginx-nginx-ssl
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: onlyoffice-onlyoffice-data
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-data
      - name: onlyoffice-onlyoffice-fonts
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-fonts
      - name: onlyoffice-onlyoffice-log
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-log
      - name: nginx-nginx-ssl
        secret:
          secretName: nginx-nginx-ssl
          items:
            - key: ca.pem
              path: "ca.pem"
            - key: cert.pem
              path: "cert.pem"
            - key: key.pem
              path: "key.pem"
