apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: onlyoffice-redis
  name: onlyoffice-redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: onlyoffice-redis
    spec:
      containers:
      - image: redis
        name: onlyoffice-redis
        resources: {}
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: onlyoffice-rabbitmq
  name: onlyoffice-rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: onlyoffice-rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: onlyoffice-rabbitmq
        resources: {}
        ports:
        - name: rabbitmq
          containerPort: 5672
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: onlyoffice-postgresql-bd
  name: onlyoffice-postgresql-bd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: onlyoffice-postgresql-bd
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: onlyoffice
        - name: POSTGRES_USER
          value: onlyoffice
        image: postgres:9.5
        name: onlyoffice-postgresql-bd
        resources: {}
        ports:
        - name: postgresql
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: onlyoffice-postgresql-bd
      restartPolicy: Always
      volumes:
      - name: onlyoffice-postgresql-bd
        persistentVolumeClaim:
          claimName: onlyoffice-postgresql-bd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: onlyoffice-documentserver
  name: onlyoffice-documentserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: onlyoffice-documentserver
    spec:
      containers:
      - env:
        - name: SSL_CERTIFICATE_PATH
          value: /mnt/cert.pem
        - name: SSL_KEY_PATH
          value: /mnt/key.pem
        - name: POSTGRESQL_SERVER_DB_NAME
          value: onlyoffice
        - name: POSTGRESQL_SERVER_HOST
          value: onlyoffice-postgresql-bd
        - name: POSTGRESQL_SERVER_PORT
          value: "5432"
        - name: POSTGRESQL_SERVER_USER
          value: onlyoffice
        - name: RABBITMQ_SERVER_URL
          value: amqp://guest:guest@onlyoffice-rabbitmq
        - name: REDIS_SERVER_HOST
          value: onlyoffice-redis
        - name: REDIS_SERVER_PORT
          value: "6379"
        image: onlyoffice/documentserver:latest
        name: onlyoffice-documentserver
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /usr/share/fonts/truetype/custom
          name: onlyoffice-onlyoffice-fonts
        - mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files
          name: onlyoffice-onlyoffice-cache
        - mountPath: /mnt/
          name: ctic-pem-ssl
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: onlyoffice-onlyoffice-fonts
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-fonts
      - name: onlyoffice-onlyoffice-cache
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-cache
      - name: ctic-pem-ssl
        secret:
          secretName: ctic-pem-ssl
          items:
            - key: ca.pem
              path: "ca.pem"
            - key: cert.pem
              path: "cert.pem"
            - key: key.pem
              path: "key.pem"
