apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: onlyoffice-haproxy
  name: onlyoffice-haproxy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  - name: "1936"
    port: 1936
    targetPort: 1936
  selector:
    io.kompose.service: onlyoffice-haproxy
status:
  loadBalancer: {}
