apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: onlyoffice-postgresql
  name: onlyoffice-postgresql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: onlyoffice-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: onlyoffice
        - name: POSTGRES_USER
          value: onlyoffice
        image: postgres:9.5
        name: onlyoffice-postgresql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgresql-data
      restartPolicy: Always
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data
status: {}
