apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: onlyoffice-rabbitmq
  name: onlyoffice-rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: onlyoffice-rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: onlyoffice-rabbitmq
        resources: {}
      restartPolicy: Always
status: {}
