apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: onlyoffice-haproxy
  name: onlyoffice-haproxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: onlyoffice-haproxy
    spec:
      containers:
      - env:
        - name: MODE
          value: http
        image: dockercloud/haproxy:1.5.1
        name: onlyoffice-haproxy
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 1936
        resources: {}
        stdin: true
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: onlyoffice-haproxy
      restartPolicy: Always
      volumes:
      - name: onlyoffice-haproxy
        persistentVolumeClaim:
          claimName: onlyoffice-haproxy
status: {}
