apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: onlyoffice-documentserver
  name: onlyoffice-documentserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: onlyoffice-documentserver
    spec:
      containers:
      - env:
        - name: BALANCE
          value: uri depth 3
        - name: EXCLUDE_PORTS
          value: "443"
        - name: EXTRA_SETTINGS
          value: http-check expect string true
        - name: HTTP_CHECK
          value: GET /healthcheck
        - name: ONLYOFFICE_DATA_CONTAINER_HOST
          value: onlyoffice-documentserver-data
        image: onlyoffice/documentserver:latest
        name: onlyoffice-documentserver
        resources: {}
        stdin: true
        volumeMounts:
        - mountPath: /var/www/onlyoffice/Data
          name: onlyoffice-onlyoffice-data
        - mountPath: /var/log/onlyoffice
          name: onlyoffice-onlyoffice-log
        - mountPath: /var/lib/onlyoffice/documentserver/App-Data/cache/files
          name: onlyoffice-onlyoffice-app
        - mountPath: /var/www/onlyoffice/documentserver-example/public/files
          name: onlyoffice-example
        - mountPath: /usr/share/fonts
          name: onlyoffice-onlyoffice-fonts
      restartPolicy: Always
      volumes:
      - name: onlyoffice-onlyoffice-data
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-data
      - name: onlyoffice-onlyoffice-log
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-log
      - name: onlyoffice-onlyoffice-app
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-app
      - name: onlyoffice-example
        persistentVolumeClaim:
          claimName: onlyoffice-example
      - name: onlyoffice-onlyoffice-fonts
        persistentVolumeClaim:
          claimName: onlyoffice-onlyoffice-fonts
status: {}
