apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: onlyoffice-documentserver-data
  name: onlyoffice-documentserver-data
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: onlyoffice-documentserver-data
status:
  loadBalancer: {}
