apiVersion: v1
kind: PersistentVolume
metadata:
  name: onlyoffice-onlyoffice-data
spec:
  capacity:
    storage: 4096Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/onlyoffice/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: onlyoffice-onlyoffice-log
spec:
  capacity:
    storage: 1029Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/onlyoffice/log
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: onlyoffice-onlyoffice-cache
spec:
  capacity:
    storage: 258Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/onlyoffice/cache
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: onlyoffice-postgresql
spec:
  capacity:
    storage: 1030Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/onlyoffice/postgresql
