apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-onlyoffice-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4096Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-onlyoffice-log
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1029Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-onlyoffice-app
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3096Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-onlyoffice-example
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 196Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-onlyoffice-fonts
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 258Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-postgresql
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1030Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-haproxy
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 230Mi
    
