apiVersion: v1
kind: Service
metadata:
  labels:
      app: onlyoffice
  name: onlyoffice
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    app: onlyoffice-documentserver-data

---
apiVersion: v1
kind: Service
metadata:
  labels:
      app: onlyoffice-documentserver
  name: onlyoffice-documentserver
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    app: onlyoffice-documentserver

---
    
apiVersion: v1
kind: Service
metadata:
  labels:
      app: onlyoffice-postgresql
  name: onlyoffice-postgresql
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
      app: onlyoffice-postgresql

---
apiVersion: v1
kind: Service
metadata:
  labels:
      app: onlyoffice-rabbitmq
  name: onlyoffice-rabbitmq
spec:
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
      app: onlyoffice-rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  labels:
      app: onlyoffice-redis
  name: onlyoffice-redis
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
      app: onlyoffice-redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: onlyoffice-haproxy
  name: onlyoffice-haproxy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  - name: "1936"
    port: 1936
    targetPort: 1936
  selector:
    app: onlyoffice-haproxy
      
