apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: openldap-openldap
  name: openldap-openldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap-openldap
      name: openldap-openldap
    spec:
      containers:
      - image: cticsjeifsc/openldap:latest
        name: openldap-openldap
        ports:
          - containerPort: 389
        volumeMounts:
          - name: openldap-openldap-etc
            mountPath: /etc/openldap/
          - name: openldap-openldap-data
            mountPath: /var/lib/openldap/openldap-data/
      volumes:
      - name: openldap-openldap-etc
        persistentVolumeClaim:
          claimName: openldap-openldap-etc
      - name: openldap-openldap-data
        persistentVolumeClaim:
          claimName: openldap-openldap-data
