apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: openldap-openldap
  name: openldap-openldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap-openldap
      name: openldap-openldap
    spec:
      containers:
      - image: cticsjeifsc/openldap:latest
        name: openldap-openldap
        ports:
          - containerPort: 389
        volumeMounts:
          - name: openldap-openldap-conf
            mountPath: /etc/openldap/slapd.conf
            subPath: slapd.conf
            readOnly: true
          - name: openldap-openldap-schema
            mountPath: /etc/openldap/schema/
            readOnly: true
          - name: openldap-openldap-data
            mountPath: /var/lib/openldap/openldap-data/
      volumes:
      - name: openldap-openldap-conf
        secret:
          secretName: openldap-openldap
      - name: openldap-openldap-schema
        configMap:
          name: openldap-openldap
          items:
            - key: core.schema
              path: "core.schema"
            - key: cosine.schema
              path: "cosine.schema"
            - key: inetorgperson.schema
              path: "inetorgperson.schema"
            - key: breduperson.schema
              path: "breduperson.schema"
      - name: openldap-openldap-data
        persistentVolumeClaim:
          claimName: openldap-openldap
