apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-openldap-etc
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/openldap/openldap/etc

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-openldap-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/openldap/openldap/data
