apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-openldap
  labels:
    app: openldap-openldap
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
