apiVersion: v1
kind: Service
metadata:
  labels:
    app: openldap
  name: openldap
spec:
  externalIPs:
    - "191.36.8.24"
    - "191.36.8.25"
  ports:
    - name: ldap
      port: 389
      protocol: TCP
      targetPort: 389
  selector:
    app: openldap-openldap
  type: LoadBalancer
