apiVersion: v1
kind: Service
metadata:
  labels:
    app: openldap
  name: openldap
spec:
  ports:
    - name: ldap
      port: 389
      protocol: TCP
      targetPort: 389
  selector:
    app: openldap-openldap
