apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-mosquitto-conf
data:
  mosquitto.conf: |-
    persistence true
    persistence_location /mosquitto/data/
    autosave_interval 60
    log_dest stdout
    listener 1883
