apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  externalIPs:
    - "191.36.8.4"
    - "191.36.8.5"
    - "191.36.8.8"
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    app: mosquitto
  type: LoadBalancer
