apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-awx-postgresql
  namespace: awx
  labels:
    app: awx-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: awx-postgresql