apiVersion: v1
kind: PersistentVolume
metadata:
  name: matchbox-data
spec:
  capacity:
    storage: 1501Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/matchbox/data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: matchbox-assets
spec:
  capacity:
    storage: 53Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/matchbox/assets
