apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: matchbox-data
  name: matchbox-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1501Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: matchbox-assets
  name: matchbox-assets
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 53Mi
