apiVersion: v1
kind: Service
metadata:
  name: matchbox
spec:
  selector:
    name: matchbox
    phase: prod
  externalIPs:
    - "191.36.8.24"
    - "191.36.8.25"
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
