apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: openproject-openproject
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: openproject-openproject
  targetCPUUtilizationPercentage: 70
