apiVersion: v1
kind: PersistentVolume
metadata:
  name: openproject-log
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  storageClassName: openproject-log
  mountOptions:
    - nolock 
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/openproject/log

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: openproject-openproject
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  storageClassName: openproject-openproject
  mountOptions:
    - nolock 
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/openproject/openproject

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: openproject-postgresql
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: openproject-postgresql
  mountOptions:
    - nolock 
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/openproject/postgresql
