apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-log
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 158Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-openproject
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2666Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-postgresql
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2667Mi
