apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-log
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
  storageClassName: openproject-log

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-openproject
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: openproject-openproject

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: openproject-postgresql
