apiVersion: v1
kind: Service
metadata:
  name: owncloud-mariadb
  labels:
    app: owncloud-mariadb
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: owncloud-mariadb

---
apiVersion: v1
kind: Service
metadata:
  name: owncloud
  labels:
    app: owncloud
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: owncloud-owncloud
