kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: netbox
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "191.36.0.0/17,2804:1454::/32"
spec:
  tls:
    - hosts:
        - netbox.sj.ifsc.edu.br
      secretName: tls-ifsc-sje
  rules:
    - host: netbox.sj.ifsc.edu.br
      http:
        paths:
          - path: /
            backend:
              serviceName: netbox
              servicePort: 80
