kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netbox-postgresql-base
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netbox-nginx-conf
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
