apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-postgresql-base
  labels:
    app: netbox
spec:
  storageClassName: srv-pool
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
