apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: samba
    dir: lib
  name: samba-lib
  namespace: testes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: samba
    dir: log
  name: samba-log
  namespace: testes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
