apiVersion: v1
kind: Service
metadata:
metadata:
  labels:
    app: samba
  name: samba-nmbd
  namespace: testes
spec:
  externalIPs:
    - "191.36.8.21"
    - "191.36.8.22"
    - "191.36.8.23"
    - "191.36.8.24"
    - "191.36.8.25"
  ports:
    - name: netbios-ns
      port: 137
      protocol: UDP
      targetPort: 137
    - name: netbios-dgm
      port: 138
      protocol: UDP
      targetPort: 138
  selector:
    app: samba
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
metadata:
  labels:
    app: samba
  name: samba-smbd
  namespace: testes
spec:
  externalIPs:
    - "191.36.8.21"
    - "191.36.8.22"
    - "191.36.8.23"
    - "191.36.8.24"
    - "191.36.8.25"
  ports:
    - name: netbios-ssn
      port: 139
      protocol: TCP
      targetPort: 139
    - name: microsoft-ds
      port: 445
      protocol: TCP
      targetPort: 445
  selector:
    app: samba
  type: LoadBalancer
