apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.2.0 (99f88ef)
  labels:
    app: nextcloud-fpm-db
  name: nextcloud-fpm-db
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: nextcloud-fpm-db
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.2.0 (99f88ef)
  labels:
    app: nextcloud-fpm-redis
  name: nextcloud-fpm-redis
spec:
  ports:
  - name: nextcloud-fpm-redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: nextcloud-fpm-redis
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.2.0 (99f88ef)
  labels:
    app: nextcloud-fpm
  name: nextcloud-fpm
spec:
  ports:
  - name: nextcloud-fpm
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: nextcloud-fpm
