apiVersion: v1
kind: PersistentVolume
metadata:
  name: nyqlab-home
spec:
  capacity:
    storage: 10011Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/home

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nyqlab-users
spec:
  capacity:
    storage: 94Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/users
