apiVersion: v1
kind: Service
metadata:
  name: nyqlab
  labels:
    app: nyqlab
spec:
spec:
  externalIPs:
    - "191.36.8.24"
    - "191.36.8.25"
  ports:
    - name: ssh
      port: 2225
      protocol: TCP
      targetPort: 22
  selector:
    app: nyqlab
  type: LoadBalancer
