version: '2'
services:
    sharelatex:
        restart: always
        image: sharelatex/sharelatex
        container_name: sharelatex
        depends_on:
            - mongo
            - redis
        privileged: true
        ports:
            - 80:80
        links:
            - mongo
            - redis
        volumes:
            - ~/sharelatex_data:/var/lib/sharelatex
        environment:
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
            SHARELATEX_REDIS_HOST: redis
            SHARELATEX_APP_NAME: Our ShareLaTeX
            

            SHARELATEX_SITE_URL: https://sharelatex.sj.ifsc.edu.br
            SHARELATEX_NAV_TITLE: ShareLaTeX do IFSC SJE
            SHARELATEX_HEADER_IMAGE_URL: http://www.sj.ifsc.edu.br/templates/campi/images/marca_saojose.png
            SHARELATEX_ADMIN_EMAIL: suporte.ti.sje@ifsc.edu.br

            # SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.sharelatex.com\">ShareLaTeX</a> 2016"},{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
            # SHARELATEX_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'

            SHARELATEX_EMAIL_FROM_ADDRESS: "ctic.sje@listas.ifsc.edu.br"


            SHARELATEX_EMAIL_SMTP_HOST: smtp.ifsc.edu.br
            SHARELATEX_EMAIL_SMTP_PORT: 465
            SHARELATEX_EMAIL_SMTP_SECURE: SSL
            SHARELATEX_EMAIL_SMTP_USER: ctic.sj
            SHARELATEX_EMAIL_SMTP_PASS: lalala
            SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
            SHARELATEX_EMAIL_SMTP_IGNORE_TLS: false
            SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by department CTIC SJE </div>"

            
    mongo:
        restart: always
        image: mongo
        container_name: mongo
        expose:
            - 27017
        volumes:
            - ~/mongo_data:/data/db

    redis:
        restart: always
        image: redis
        container_name: redis
        expose:
            - 6379
        volumes:
            - ~/redis_data:/data
