apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sharelatex-sharelatex
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: sharelatex-sharelatex
  targetCPUUtilizationPercentage: 75
