apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharelatex-mongo-pv
spec:
  capacity:
    storage: 150Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/sharelatex/mongo
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharelatex-redis-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/sharelatex/redis
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharelatex-sharelatex-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/sharelatex/sharelatex
