apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharelatex-mongo-base
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 150Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharelatex-redis-base
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharelatex-sharelatex-arquivos
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
