apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nextcloud-fpm-mariadb
  labels:
    app: nextcloud-fpm-mariadb
spec:
  template:
    metadata:
      labels:
        app: nextcloud-fpm-mariadb
      annotations:
        pod.alpha.kubernetes.io/init-containers: '
          [
            {
              "name": "copy-custom-config",
              "image": "bitnami/mariadb:10.1.23-r2",
              "command": ["sh", "-c", "mkdir -p /bitnami/mariadb/conf && cp -n /bitnami/mariadb_config/my.cnf /bitnami/mariadb/conf/my_custom.cnf"],
              "volumeMounts": [
                {
                  "name": "config",
                  "mountPath": "/bitnami/mariadb_config"
                },
                {
                  "name": "data",
                  "mountPath": "/bitnami/mariadb"
                }
              ]
            }
          ]'
    spec:
      containers:
      - name: nextcloud-fpm-mariadb
        image: "bitnami/mariadb:10.1.23-r2"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-fpm-db
              key: db-root-password
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-fpm-db
              key: db-password
        - name: MARIADB_DATABASE
          value: nextcloud
        - name: MARIADB_USER
          value: nextcloud
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
      volumes:
      - name: config
        configMap:
          name: nextcloud-fpm-cfg
      - name: data
        persistentVolumeClaim:
          claimName: nextcloud-fpm-mariadb
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nextcloud-fpm-redis
  name: nextcloud-fpm-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud-fpm-redis
    spec:
      containers:
      - image: redis:alpine
        name: nextcloud-fpm-redis
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /data
          name: nextcloud-fpm-redis
      restartPolicy: Always
      volumes:
      - name: nextcloud-fpm-redis
        persistentVolumeClaim:
          claimName: nextcloud-fpm-redis

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.2.0 (99f88ef)
  labels:
    app: nextcloud-fpm-app
  name: nextcloud-fpm-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud-fpm-app
    spec:
      containers:
      - image: nextcloud:fpm
        name: nextcloud-fpm-app
        command: ["/bin/sh","-c", "apt-get update && apt-get -y -q install smbclient && php-fpm"]
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud-fpm-data
      restartPolicy: Always
      volumes:
      - name: nextcloud-fpm-data
        persistentVolumeClaim:
          claimName: nextcloud-fpm-data
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.2.0 (99f88ef)
  labels:
    app: nextcloud-fpm-web
  name: nextcloud-fpm-web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud-fpm-web
    spec:
      containers:
      - image: nginx
        name: nextcloud-fpm-web
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: nextcloud-fpm-web
          readOnly: true
        - mountPath: /var/www/html
          name: nextcloud-fpm-data
      restartPolicy: Always
      volumes:
      - name: nextcloud-fpm-web
        persistentVolumeClaim:
          claimName: nextcloud-fpm-web
          readOnly: true
      - name: nextcloud-fpm-data
        persistentVolumeClaim:
          claimName: nextcloud-fpm-data
