apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-fpm-db
spec:
  capacity:
    storage: 635Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/nextcloud_fpm/db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-fpm-web
spec:
  capacity:
    storage: 636Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/nextcloud_fpm/web
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-fpm-data
spec:
  capacity:
    storage: 637Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/nextcloud_fpm/nextcloud
