apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud-fpm-db
  name: nextcloud-fpm-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 635Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud-fpm-web
  name: nextcloud-fpm-web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 636Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nextcloud-fpm-data
  name: nextcloud-fpm-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 637Mi
