# subpath https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: matlab
  labels:
    app: matlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: matlab
    spec:
      containers:
      - name: matlab
        image: cticsjeifsc/matlab
        ports:
        - name: ssh
          containerPort: 22
        resources:
          requests:
            cpu: "10"
            memory: 16Gi
        volumeMounts:
        - name: matlab-root
          mountPath: /opt
        - name: matlab-home
          mountPath: /home
        - name: matlab-users
          mountPath: /etc/shadow
          subPath: shadow
        - name: matlab-users
          mountPath: /etc/passwd
          subPath: passwd
        - name: matlab-users
          mountPath: /etc/group
          subPath: group
          
        - name: nsswitch-ldap-conf
          mountPath: /etc/nsswitch.conf
          subPath: nsswitch.conf
          
        - name: libnss-ldap
          mountPath: /etc/libnss-ldap.conf
          subPath: libnss-ldap.conf
        - name: pam-ldap
          mountPath: /etc/pam_ldap.conf
          subPath: pam_ldap.conf
        - name: ldap-conf
          mountPath: /etc/ldap.conf
          subPath: ldap.conf
          
        - name: pam-ldap-conf
          mountPath: /etc/pam.d/

      volumes:
      - name: matlab-root
        persistentVolumeClaim:
          claimName: matlab-root
      - name: matlab-home
        persistentVolumeClaim:
          claimName: matlab-home
      - name: matlab-users
        persistentVolumeClaim:
          claimName: matlab-users
          
      - name: nsswitch-ldap-conf
        configMap:
          name: nsswitch-ldap-conf
          
      - name: libnss-ldap
        configMap:
          name: ldap-conf
      - name: pam-ldap
        configMap:
          name: ldap-conf
      - name: ldap-conf
        configMap:
          name: ldap-conf
          
          
      - name: pam-ldap-conf
        configMap:
          name: pam-ldap-conf
          items:
            - key: common-session
              path: "common-session"
            - key: common-account
              path: "common-account"
            - key: common-auth
              path: "common-auth"
            - key: common-password
              path: "common-password"
            - key: common-session-noninteractive
              path: "common-session-noninteractive"
