# subpath https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: matlab
  labels:
    app: matlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: matlab
    spec:
      containers:
      - name: matlab
        image: boidacarapreta/matlab:latest
        ports:
        - name: ssh
          containerPort: 22
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 5Gi
        volumeMounts:
        - name: matlab-root
          mountPath: /opt
        - name: matlab-home
          mountPath: /home
        - name: matlab-users
          mountPath: /etc/shadow
          subPath: shadow
        - name: matlab-users
          mountPath: /etc/passwd
          subPath: passwd
        - name: matlab-users
          mountPath: /etc/group
          subPath: group
      volumes:
      - name: matlab-root
        persistentVolumeClaim:
          claimName: matlab-root
      - name: matlab-home
        persistentVolumeClaim:
          claimName: matlab-home
      - name: matlab-users
        persistentVolumeClaim:
          claimName: matlab-users
