apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: matlab
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: matlab
  targetCPUUtilizationPercentage: 80
