apiVersion: v1
kind: PersistentVolume
metadata:
  name: matlab-root
spec:
  capacity:
    storage: 8205Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/matlab/root/

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: matlab-home
spec:
  capacity:
    storage: 10011Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/home

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: matlab-users
spec:
  capacity:
    storage: 94Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/users
